//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBAGitAddin.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VBAGitUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VBAGitUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBAGitAddin.UI.VBAGitUI", typeof(VBAGitUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        internal static string BrowseReferencesForm_BranchName {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Branch.
        /// </summary>
        internal static string BrowseReferencesForm_CurrentBranch {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_CurrentBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Commit.
        /// </summary>
        internal static string BrowseReferencesForm_DateLastCommit {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_DateLastCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string BrowseReferencesForm_Description {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter: .
        /// </summary>
        internal static string BrowseReferencesForm_Filter {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Refname, Subject, Authors, SHA-1.
        /// </summary>
        internal static string BrowseReferencesForm_FilterTooltip {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_FilterTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Author.
        /// </summary>
        internal static string BrowseReferencesForm_LastAuthor {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_LastAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Commit.
        /// </summary>
        internal static string BrowseReferencesForm_LastCommit {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_LastCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-1.
        /// </summary>
        internal static string BrowseReferencesForm_SHA1 {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show nested refs.
        /// </summary>
        internal static string BrowseReferencesForm_ShowNestedRefs {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_ShowNestedRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked branch.
        /// </summary>
        internal static string BrowseReferencesForm_TrackedBranch {
            get {
                return ResourceManager.GetString("BrowseReferencesForm_TrackedBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Signed-off-by.
        /// </summary>
        internal static string CommitForm_AddSignedoffby {
            get {
                return ResourceManager.GetString("CommitForm_AddSignedoffby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string CommitForm_CheckAdded {
            get {
                return ResourceManager.GetString("CommitForm_CheckAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string CommitForm_CheckAll {
            get {
                return ResourceManager.GetString("CommitForm_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string CommitForm_CheckDeleted {
            get {
                return ResourceManager.GetString("CommitForm_CheckDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string CommitForm_CheckModified {
            get {
                return ResourceManager.GetString("CommitForm_CheckModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string CommitForm_CheckNone {
            get {
                return ResourceManager.GetString("CommitForm_CheckNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unversioned.
        /// </summary>
        internal static string CommitForm_CheckUnversioned {
            get {
                return ResourceManager.GetString("CommitForm_CheckUnversioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versioned.
        /// </summary>
        internal static string CommitForm_CheckVersioned {
            get {
                return ResourceManager.GetString("CommitForm_CheckVersioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string CommitForm_Commit {
            get {
                return ResourceManager.GetString("CommitForm_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were changed or added  since the last commit.
        /// </summary>
        internal static string CommitForm_EmptyCommitList {
            get {
                return ResourceManager.GetString("CommitForm_EmptyCommitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes made (double-click on file for diff): .
        /// </summary>
        internal static string CommitForm_GroupChanges {
            get {
                return ResourceManager.GetString("CommitForm_GroupChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: .
        /// </summary>
        internal static string CommitForm_GroupMessage {
            get {
                return ResourceManager.GetString("CommitForm_GroupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check: .
        /// </summary>
        internal static string CommitForm_LabelCheck {
            get {
                return ResourceManager.GetString("CommitForm_LabelCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit to: .
        /// </summary>
        internal static string CommitForm_LabelCommit {
            get {
                return ResourceManager.GetString("CommitForm_LabelCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected, {1} total.
        /// </summary>
        internal static string CommitForm_LabelSelected {
            get {
                return ResourceManager.GetString("CommitForm_LabelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message only.
        /// </summary>
        internal static string CommitForm_MessageOnly {
            get {
                return ResourceManager.GetString("CommitForm_MessageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new branch.
        /// </summary>
        internal static string CommitForm_NewBranch {
            get {
                return ResourceManager.GetString("CommitForm_NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set author.
        /// </summary>
        internal static string CommitForm_SetAuthor {
            get {
                return ResourceManager.GetString("CommitForm_SetAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set author date.
        /// </summary>
        internal static string CommitForm_SetAuthorDate {
            get {
                return ResourceManager.GetString("CommitForm_SetAuthorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Unversioned Files.
        /// </summary>
        internal static string CommitForm_ShowUnversionedFiles {
            get {
                return ResourceManager.GetString("CommitForm_ShowUnversionedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed-off-by: {0}.
        /// </summary>
        internal static string CommitForm_Signedofby {
            get {
                return ResourceManager.GetString("CommitForm_Signedofby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Commit - VBAGit.
        /// </summary>
        internal static string CommitForm_Text {
            get {
                return ResourceManager.GetString("CommitForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while updating files status....
        /// </summary>
        internal static string CommitForm_WaitForUpdate {
            get {
                return ResourceManager.GetString("CommitForm_WaitForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base On.
        /// </summary>
        internal static string CreateBranchForm_BaseOn {
            get {
                return ResourceManager.GetString("CreateBranchForm_BaseOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string CreateBranchForm_Branch {
            get {
                return ResourceManager.GetString("CreateBranchForm_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string CreateBranchForm_Commit {
            get {
                return ResourceManager.GetString("CreateBranchForm_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string CreateBranchForm_Description {
            get {
                return ResourceManager.GetString("CreateBranchForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        internal static string CreateBranchForm_Force {
            get {
                return ResourceManager.GetString("CreateBranchForm_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAD ({0}).
        /// </summary>
        internal static string CreateBranchForm_Head {
            get {
                return ResourceManager.GetString("CreateBranchForm_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CreateBranchForm_Name {
            get {
                return ResourceManager.GetString("CreateBranchForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string CreateBranchForm_Options {
            get {
                return ResourceManager.GetString("CreateBranchForm_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to new branch.
        /// </summary>
        internal static string CreateBranchForm_Switch {
            get {
                return ResourceManager.GetString("CreateBranchForm_Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string CreateBranchForm_Tag {
            get {
                return ResourceManager.GetString("CreateBranchForm_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Create Branch - VBAGit.
        /// </summary>
        internal static string CreateBranchForm_Text {
            get {
                return ResourceManager.GetString("CreateBranchForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string CreateBranchForm_Track {
            get {
                return ResourceManager.GetString("CreateBranchForm_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch already exists.
        /// </summary>
        internal static string Git_BranchExists {
            get {
                return ResourceManager.GetString("Git_BranchExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid branch name.
        /// </summary>
        internal static string Git_InvalidBranchName {
            get {
                return ResourceManager.GetString("Git_InvalidBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized empty Git repository in {0}.
        /// </summary>
        internal static string Git_SuccessfulInitEmptyRepo {
            get {
                return ResourceManager.GetString("Git_SuccessfulInitEmptyRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No To All.
        /// </summary>
        internal static string NoToAll {
            get {
                return ResourceManager.GetString("NoToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - VBAGit.
        /// </summary>
        internal static string ProgressForm_Text {
            get {
                return ResourceManager.GetString("ProgressForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit....
        /// </summary>
        internal static string ProgressInfo_Commit {
            get {
                return ResourceManager.GetString("ProgressInfo_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch....
        /// </summary>
        internal static string ProgressInfo_CreateBranch {
            get {
                return ResourceManager.GetString("ProgressInfo_CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting files....
        /// </summary>
        internal static string ProgressInfo_ExportingFiles {
            get {
                return ResourceManager.GetString("ProgressInfo_ExportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///This file has been modified outside of the source editor.
        ///Do you want to reload it?.
        /// </summary>
        internal static string ReloadFileForm_Info {
            get {
                return ResourceManager.GetString("ReloadFileForm_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit.
        /// </summary>
        internal static string VBAGitCaption {
            get {
                return ResourceManager.GetString("VBAGitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .VBAGit.
        /// </summary>
        internal static string VBAGitFolder {
            get {
                return ResourceManager.GetString("VBAGitFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit Add-In could not be loaded.
        /// </summary>
        internal static string VBAGitLoadFailure {
            get {
                return ResourceManager.GetString("VBAGitLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        internal static string VBAGitMenu {
            get {
                return ResourceManager.GetString("VBAGitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string VBAGitMenu_About {
            get {
                return ResourceManager.GetString("VBAGitMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for modifications.
        /// </summary>
        internal static string VBAGitMenu_CheckForModifications {
            get {
                return ResourceManager.GetString("VBAGitMenu_CheckForModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swicth/Checkout....
        /// </summary>
        internal static string VBAGitMenu_Checkout {
            get {
                return ResourceManager.GetString("VBAGitMenu_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up....
        /// </summary>
        internal static string VBAGitMenu_CleanUp {
            get {
                return ResourceManager.GetString("VBAGitMenu_CleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git &amp;Commit....
        /// </summary>
        internal static string VBAGitMenu_Commit {
            get {
                return ResourceManager.GetString("VBAGitMenu_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git create repositor&amp;y....
        /// </summary>
        internal static string VBAGitMenu_Create {
            get {
                return ResourceManager.GetString("VBAGitMenu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch....
        /// </summary>
        internal static string VBAGitMenu_CreateBranch {
            get {
                return ResourceManager.GetString("VBAGitMenu_CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string VBAGitMenu_Delete {
            get {
                return ResourceManager.GetString("VBAGitMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff.
        /// </summary>
        internal static string VBAGitMenu_Diff {
            get {
                return ResourceManager.GetString("VBAGitMenu_Diff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string VBAGitMenu_Export {
            get {
                return ResourceManager.GetString("VBAGitMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        internal static string VBAGitMenu_Fecth {
            get {
                return ResourceManager.GetString("VBAGitMenu_Fecth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge....
        /// </summary>
        internal static string VBAGitMenu_Merge {
            get {
                return ResourceManager.GetString("VBAGitMenu_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string VBAGitMenu_Pull {
            get {
                return ResourceManager.GetString("VBAGitMenu_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string VBAGitMenu_Push {
            get {
                return ResourceManager.GetString("VBAGitMenu_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebase....
        /// </summary>
        internal static string VBAGitMenu_Rebase {
            get {
                return ResourceManager.GetString("VBAGitMenu_Rebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo-browser.
        /// </summary>
        internal static string VBAGitMenu_RepoBrowser {
            get {
                return ResourceManager.GetString("VBAGitMenu_RepoBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve....
        /// </summary>
        internal static string VBAGitMenu_Resolve {
            get {
                return ResourceManager.GetString("VBAGitMenu_Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert....
        /// </summary>
        internal static string VBAGitMenu_Revert {
            get {
                return ResourceManager.GetString("VBAGitMenu_Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string VBAGitMenu_Settings {
            get {
                return ResourceManager.GetString("VBAGitMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        internal static string VBAGitMenu_ShowLog {
            get {
                return ResourceManager.GetString("VBAGitMenu_ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git &amp;Sync....
        /// </summary>
        internal static string VBAGitMenu_Sync {
            get {
                return ResourceManager.GetString("VBAGitMenu_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit.
        /// </summary>
        internal static string VBAGitMenu_VBAGit {
            get {
                return ResourceManager.GetString("VBAGitMenu_VBAGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes To All.
        /// </summary>
        internal static string YesToAll {
            get {
                return ResourceManager.GetString("YesToAll", resourceCulture);
            }
        }
    }
}
