//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBAGitAddin.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VBAGitUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VBAGitUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBAGitAddin.UI.VBAGitUI", typeof(VBAGitUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Ducky {
            get {
                object obj = ResourceManager.GetObject("Ducky", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK_AllCaps {
            get {
                return ResourceManager.GetString("OK_AllCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes File.
        /// </summary>
        internal static string SourceControl_AttributesFile {
            get {
                return ResourceManager.GetString("SourceControl_AttributesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        internal static string SourceControl_Branches {
            get {
                return ResourceManager.GetString("SourceControl_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SourceControl_CancelGlobalSettings {
            get {
                return ResourceManager.GetString("SourceControl_CancelGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        internal static string SourceControl_Changes {
            get {
                return ResourceManager.GetString("SourceControl_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string SourceControl_Commit {
            get {
                return ResourceManager.GetString("SourceControl_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string SourceControl_CommitButtonLabel {
            get {
                return ResourceManager.GetString("SourceControl_CommitButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit message:.
        /// </summary>
        internal static string SourceControl_CommitMessageLabel {
            get {
                return ResourceManager.GetString("SourceControl_CommitMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit and Push.
        /// </summary>
        internal static string SourceControl_CommitPush {
            get {
                return ResourceManager.GetString("SourceControl_CommitPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit and Sync.
        /// </summary>
        internal static string SourceControl_CommitSync {
            get {
                return ResourceManager.GetString("SourceControl_CommitSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit - Create Branch.
        /// </summary>
        internal static string SourceControl_CreateNewBranchCaption {
            get {
                return ResourceManager.GetString("SourceControl_CreateNewBranchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify branch name..
        /// </summary>
        internal static string SourceControl_CreateNewBranchInstructions {
            get {
                return ResourceManager.GetString("SourceControl_CreateNewBranchInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New branch.
        /// </summary>
        internal static string SourceControl_CreateNewBranchTitle {
            get {
                return ResourceManager.GetString("SourceControl_CreateNewBranchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Repository.
        /// </summary>
        internal static string SourceControl_CreateNewRepo {
            get {
                return ResourceManager.GetString("SourceControl_CreateNewRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch:.
        /// </summary>
        internal static string SourceControl_CurrentBranchLabel {
            get {
                return ResourceManager.GetString("SourceControl_CurrentBranchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Repository Location.
        /// </summary>
        internal static string SourceControl_DefaultRepoLocationLabel {
            get {
                return ResourceManager.GetString("SourceControl_DefaultRepoLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit - Delete Branch.
        /// </summary>
        internal static string SourceControl_DeleteBranchCaption {
            get {
                return ResourceManager.GetString("SourceControl_DeleteBranchCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify branch name..
        /// </summary>
        internal static string SourceControl_DeleteBranchInstructionsLabel {
            get {
                return ResourceManager.GetString("SourceControl_DeleteBranchInstructionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete branch.
        /// </summary>
        internal static string SourceControl_DeleteBranchTitleLable {
            get {
                return ResourceManager.GetString("SourceControl_DeleteBranchTitleLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string SourceControl_DestinationLabel {
            get {
                return ResourceManager.GetString("SourceControl_DestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string SourceControl_EmailAddressLabel {
            get {
                return ResourceManager.GetString("SourceControl_EmailAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded changes.
        /// </summary>
        internal static string SourceControl_ExcludedChanges {
            get {
                return ResourceManager.GetString("SourceControl_ExcludedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        internal static string SourceControl_FetchCommitsLabel {
            get {
                return ResourceManager.GetString("SourceControl_FetchCommitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string SourceControl_GlobalSettings {
            get {
                return ResourceManager.GetString("SourceControl_GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore File.
        /// </summary>
        internal static string SourceControl_IgnoreFile {
            get {
                return ResourceManager.GetString("SourceControl_IgnoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included changes.
        /// </summary>
        internal static string SourceControl_IncludedChanges {
            get {
                return ResourceManager.GetString("SourceControl_IncludedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming commits.
        /// </summary>
        internal static string SourceControl_IncomingCommits {
            get {
                return ResourceManager.GetString("SourceControl_IncomingCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init New Repo from this Project.
        /// </summary>
        internal static string SourceControl_InitRepoButtonToolTip {
            get {
                return ResourceManager.GetString("SourceControl_InitRepoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string SourceControl_MergeBranch {
            get {
                return ResourceManager.GetString("SourceControl_MergeBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit - Merge.
        /// </summary>
        internal static string SourceControl_MergeFormCaption {
            get {
                return ResourceManager.GetString("SourceControl_MergeFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select source and destination branches..
        /// </summary>
        internal static string SourceControl_MergeFormInstructions {
            get {
                return ResourceManager.GetString("SourceControl_MergeFormInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge branches.
        /// </summary>
        internal static string SourceControl_MergeFormTitle {
            get {
                return ResourceManager.GetString("SourceControl_MergeFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Branch.
        /// </summary>
        internal static string SourceControl_NewBranch {
            get {
                return ResourceManager.GetString("SourceControl_NewBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repository found..
        /// </summary>
        internal static string SourceControl_NoRepoFound {
            get {
                return ResourceManager.GetString("SourceControl_NoRepoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Working Directory.
        /// </summary>
        internal static string SourceControl_OpenWorkingDirectory {
            get {
                return ResourceManager.GetString("SourceControl_OpenWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Working Directory.
        /// </summary>
        internal static string SourceControl_OpenWorkingFolderToolTip {
            get {
                return ResourceManager.GetString("SourceControl_OpenWorkingFolderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing commits.
        /// </summary>
        internal static string SourceControl_OutgoingCommits {
            get {
                return ResourceManager.GetString("SourceControl_OutgoingCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Branches.
        /// </summary>
        internal static string SourceControl_PublishedBranchesLabel {
            get {
                return ResourceManager.GetString("SourceControl_PublishedBranchesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string SourceControl_PullCommitsLabel {
            get {
                return ResourceManager.GetString("SourceControl_PullCommitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string SourceControl_PushCommitsLabel {
            get {
                return ResourceManager.GetString("SourceControl_PushCommitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes pending changes.
        /// </summary>
        internal static string SourceControl_RefreshButtonToolTip {
            get {
                return ResourceManager.GetString("SourceControl_RefreshButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Settings.
        /// </summary>
        internal static string SourceControl_RespositorySettings {
            get {
                return ResourceManager.GetString("SourceControl_RespositorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SourceControl_Settings {
            get {
                return ResourceManager.GetString("SourceControl_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceControl_SourceLabel {
            get {
                return ResourceManager.GetString("SourceControl_SourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Merged {0} into {1}.
        /// </summary>
        internal static string SourceControl_SuccessfulMerge {
            get {
                return ResourceManager.GetString("SourceControl_SuccessfulMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string SourceControl_SyncCommitsLabel {
            get {
                return ResourceManager.GetString("SourceControl_SyncCommitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublished Branches.
        /// </summary>
        internal static string SourceControl_UnpublishedBranchesLabel {
            get {
                return ResourceManager.GetString("SourceControl_UnpublishedBranchesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsynced commits.
        /// </summary>
        internal static string SourceControl_UnsyncedCommits {
            get {
                return ResourceManager.GetString("SourceControl_UnsyncedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untracked files.
        /// </summary>
        internal static string SourceControl_UntrackedFiles {
            get {
                return ResourceManager.GetString("SourceControl_UntrackedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string SourceControl_UpdateGlobalSettings {
            get {
                return ResourceManager.GetString("SourceControl_UpdateGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string SourceControl_UserNameLabel {
            get {
                return ResourceManager.GetString("SourceControl_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Control.
        /// </summary>
        internal static string SourceControlPanel_Caption {
            get {
                return ResourceManager.GetString("SourceControlPanel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of unassigned variable &apos;{0}&apos;.
        /// </summary>
        internal static string UnassignedVariableUsage_ {
            get {
                return ResourceManager.GetString("UnassignedVariableUsage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0} ({1}).
        /// </summary>
        internal static string VBAGit_AboutBuild {
            get {
                return ResourceManager.GetString("VBAGit_AboutBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit Add-In could not be loaded.
        /// </summary>
        internal static string VBAGitLoadFailure {
            get {
                return ResourceManager.GetString("VBAGitLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git.
        /// </summary>
        internal static string VBAGitMenu {
            get {
                return ResourceManager.GetString("VBAGitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About....
        /// </summary>
        internal static string VBAGitMenu_About {
            get {
                return ResourceManager.GetString("VBAGitMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git &amp;Commit....
        /// </summary>
        internal static string VBAGitMenu_Commit {
            get {
                return ResourceManager.GetString("VBAGitMenu_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git create repositor&amp;y....
        /// </summary>
        internal static string VBAGitMenu_Create {
            get {
                return ResourceManager.GetString("VBAGitMenu_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        internal static string VBAGitMenu_Fecth {
            get {
                return ResourceManager.GetString("VBAGitMenu_Fecth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        internal static string VBAGitMenu_Pull {
            get {
                return ResourceManager.GetString("VBAGitMenu_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        internal static string VBAGitMenu_Push {
            get {
                return ResourceManager.GetString("VBAGitMenu_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Git &amp;Sync....
        /// </summary>
        internal static string VBAGitMenu_Sync {
            get {
                return ResourceManager.GetString("VBAGitMenu_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBAGit.
        /// </summary>
        internal static string VBAGitMenu_VBAGit {
            get {
                return ResourceManager.GetString("VBAGitMenu_VBAGit", resourceCulture);
            }
        }
    }
}
